# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\projects\gmpy2-feedstock\recipe, last modified Mon Oct 15 09:44:56 2018
# ------------------------------------------------

package:
    name: gmpy2
    version: 2.1.0a1
source:
    patches:
        - typo_fix.patch
    git_url: https://github.com/aleaxit/gmpy.git
    git_rev: gmpy2-2.1.0a1
build:
    number: '1003'
channels:
  - msys2
  - local

requirements:
  build:
    - m2w64-gcc-libs
    - posix
    - m2w64-gcc 
    - m2-autoconf
    - m2w64-tools-git
    - mpc >=1.0.0
    - mpfr >=4.0.1
    - mpir >=3.0.0
    - cython
  run:
    - m2w64-gcc-libs
    - mpc >=1.0.0
    - mpfr >=4.0.1
    - mpir >=3.0.0
test:
    imports:
        - gmpy2
about:
    home: https://pypi.python.org/pypi/gmpy2
    license: LGPL 3
    license_file: COPYING.LESSER
    summary: GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
