
package:
    name: gmpy2
    version: 2.1.0a4_fix
source:
    patches:
        - fix.patch
        - fix_ignore_typecheck.patch
    git_url: https://github.com/aleaxit/gmpy.git
    git_rev: b6a8ea6188352139a7d28342ee4630e14c65b7e5
build:
    number: '1'
channels:
  - msys2
  - local

requirements:
  build:
    - m2w64-gcc-libs
    - posix
    - m2w64-gcc 
    - m2-autoconf
    - m2w64-tools-git
    - m2w64-mpc >=1.0.0
    - m2w64-mpfr >=3.0.0
    - cython
    - patch
  run:
    - m2w64-gcc-libs
    - m2w64-mpc >=1.0.0
    - m2w64-mpfr >=3.0.0
test:
    imports:
        - gmpy2
about:
    home: https://pypi.python.org/pypi/gmpy2
    license: LGPL 3
    license_file: COPYING.LESSER
    summary: GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x

