
export C_INCLUDE_PATH=$UNIX_STYLE_BUILD_PREFIX/Library/include:$UNIX_STYLE_BUILD_PREFIX/include
export CPLUS_INCLUDE_PATH=$UNIX_STYLE_BUILD_PREFIX/Library/include:$UNIX_STYLE_BUILD_PREFIX/include

export LDFLAGS="-M"

export LIBRARY_PATH="$UNIX_STYLE_RECIPE_DIR/lib:$UNIX_STYLE_BUILD_PREFIX/Library/lib"

